run:
  timeout: 5m
  go: '1.21'

output:
  formats:
    - format: colored-line-number
      path: stdout

linters:
  enable:
    - gofmt
    - goimports
    - govet
    - errcheck
    - staticcheck
    - unused
    - gosimple
    - ineffassign
    - typecheck
    - gosec
    - misspell
    - unconvert
    - dupl
    - goconst
    - gocyclo
    - gofumpt
    - revive
  disable:
    - deadcode    # Deprecated, replaced by unused
    - structcheck # Deprecated, replaced by unused
    - varcheck    # Deprecated, replaced by unused

linters-settings:
  gocyclo:
    min-complexity: 15
  dupl:
    threshold: 100
  goconst:
    min-len: 3
    min-occurrences: 3

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - gosec
        - dupl